### ISSUE TITLE
add chapter indicator to scroll view

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#1269]
We already have some simple functionality for this but there is a lot of room for improvement. We could use something like this https://github.com/danoz73/RecyclerViewFastScroller or this https://github.com/AnderWeb/discreteSeekBar

**Comment by PhotoNomad0** [comment]
@neutrinog - I notice that currently the chapter numbers only work in read mode, not in any chunk mode.

**Comment by neutrinog** [comment]
I don't remember if that was intentional or not. For now we can just continue with the read mode and add it to the chunk mode later. We can ask in our next meeting.

**Comment by PhotoNomad0** [comment]
@neutrinog -  It looks like there was no chapter indication on the chunk and review modes because the chapter numbers were just guesstimated.  As a first step I added a method to the adapters to report the chapter associated with a position.  So now have chapter numbers working for all view modes.  Next I am looking at using the RecyclerViewFastScroller.  It seems more intuitive to me than to have scroll bar separate from recycle views.

**Comment by neutrinog** [comment]
excellent!

**Comment by PhotoNomad0** [comment]
I have made progress on it.  Have to make a couple fixes to the library.  Have a pull request submitted for scroll to bottom. Working on a second fix to work with the large chapter cards.

**Comment by cckozie** [comment]
Did this get missed in the build? I am not seeing the chapter indicator in any mode.

**Comment by PhotoNomad0** [comment]
@cckozie - this is working for me.

**Comment by cckozie** [comment]
I failed this issue because the chapter indicator is not displayed when scrolling by swiping (my normal way to scroll). Since this was not detailed in the issue, I'll pass it for now and add a new issue to complete the implementation.
