### ISSUE TITLE
Provide feedback on publishing to user

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-android#1455]
Nathaniel is a translator. He uses translationStudio to translate a few chapters during a MAST event. His team also translates other chapters during the same event. They all upload their work but are confused at the usage of the word Publish. After he realizes that he cannot find any other way to upload their work, they decide to use the Publish feature. After they publish they are confused and do not know where their work went. They Publish again just to see if they missed something. They contact their project manager and their MAST coordinator to get help. They ask around and are left wondering what to do. They would like a way to upload their work and have a link to see where it went. They would also like direction on what to do for next steps.

**Comment by PhotoNomad0** [comment]
Will add URL to Publish Success dialog in example format:

https://server/username/translation_id

example:

https://git.door43.org/photonomad0/en_exo_text_reg

**Comment by cckozie** [comment]
The feed back when successfully uploading is good, but when there is a failure, the error message does not give the user any idea of what went wrong or how to possibly correct it.
![screenshot_2016-05-19-13-19-35](https://cloud.githubusercontent.com/assets/8171759/15404775/ad3bdf7c-1dc4-11e6-89cf-47a98aef2777.png)

Checking with Klappy to see if he really wants something in the feedback about "direction on what to do for next steps".

**Comment by neutrinog** [comment]
If the user chooses to report a bug the actual error log is submitted to the developers. In this particular case there's nothing to tell the user that will help them fix their upload. So just submitting a bug report is the best solution.

**Comment by RRohrssen** [comment]
@Joel, I think the feedback is on the success or failure of submitting the
big report, not the original big submitted. In other words if a user is not
connected and tries to submit a report, that submission is a failure. Is it
possible to queue those submissions, or give the user feedback that bugs
commit be submitted without a connection?

Ron Rohrssen

**Comment by neutrinog** [comment]
no right now we don't have a way to queue bug reports. Also there's already an issue open to display an error if a bug report fails to send. https://github.com/unfoldingWord-dev/ts-android/issues/953

**Comment by cckozie** [comment]
The user story (and my comments) are not related to submitting a bug report. I'm surprised that we can't give the user anymore explanation than "Upload failed". Can't we tell whether it was a connection problem or something that prevented us from writing the files or something like that. Seems to me that we could suggest that they try again or do the "Report Bug" (is this failure really a bug??) or maybe something else as appropriate based on what caused the error.

**Comment by PhotoNomad0** [comment]
@cckozie @RRohrssen  - anything is possible given enough time.  Will check to see if how much effort it will take to propagate errors from third party libraries up to user, but then the bigger issue will be to show the errors in a way that is understandable by the end user.  Also it is an interesting problem how to report a bug when there is no internet connectivity.  I can see queuing them growing into a big task.  Then do you remind the user from time to time?  I don't think we want to send anything without again asking permission since there may be costs and bandwidth limitations involved in a remote location.

**Comment by PhotoNomad0** [comment]
@cckozie @neutrinog @RRohrssen   - what we get back on an upload failure are only a few possible exceptions thrown by the git library:

- IOException - issue accessing files on local device.  If this happens we have major issues.
- CheckoutConflictException - problem merging changes due to unresolved conflicts in one of the chunk files.  Giving them useful direction how to resolve this would be very complicated.  They also shouldn't get into this state as it should be managed by the app.
- GitAPIException - a catch all for all other issues including communication problems.  There is a description string attached to it but that may not be useful to the user.  These are for the library developer's use and are not documented.  We might be able to catch these and map them to translatable strings.  That is building our house on the sand.

The problem with wireless internet is that there are so many failure modes.  For example:

- No WIFI connection - we already have a check for this and we show a snackbar popup.  This should probably be changed to a popup dialog since it could be missed by user.

Many possible failures with WIFI connections:
- weak WIFI signal packets being dropped - looks to us like the server didn't respond.  Get a timeout.
- congested internet - just times out.
- connection drops out in the middle of data transfer - just times out.
- no internet gateway or route to door43 server - several possible causes here.  Could probably do a ping to see if door43 is accessible.  But we may need to wait for a while, because if it is not the request will just time out.
- door43 server down or overloaded with requests - just times out.

How should we proceed here?

**Comment by neutrinog** [comment]
I do not agree it is beneficial to display any additional information to the user in this particular case. Except possibly in the case of wifi being unstable, but if that's the case we technically need to apply that to everywhere else we use wifi. However, the amount of data we are dealing with on an upload is so small I do not think it would be worth it.

The checkout conflict is something that just needs to be fixed so it no longer happens rather than displaying an error to the user.

90% of the possible issues will require developer intervention. Therefore asking them to send a bug report is the best solution.
