### ISSUE TITLE
Unhelpful message when trying to create a door43 account

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1548]
When attempting to create a door43 account that already exists, the error message just states: Error Your account could not be created. 
The message should be something more like: An account for email address xxxxxxxxxx already exists.

**Comment by neutrinog** [comment]
@cckozie this is not reliably possible within the app because the error message received from the server is not helpful. The actual response from the server is 
```
java.io.FileNotFoundException: https://git.door43.org/api/v1/admin/users
```

Therefore the best we can do is tell the user that an error occurred. We could guess that an account already exists, however that may not always be correct.

**Comment by neutrinog** [comment]
@richmahn could we update the gogs api to allow searching for users by email?

**Comment by richmahn** [comment]
@neutrinog that should be possible.

**Comment by neutrinog** [comment]
@richmahn does the api support searching for users by email now?

**Comment by cckozie** [comment]
This is what I get when I attempt to create a duplicate account on tS Desktop
![image](https://cloud.githubusercontent.com/assets/8171759/22209051/b3b121c4-e14a-11e6-99c5-6b296816cc74.png)

**Comment by cckozie** [comment]
This has been fixed.
