### ISSUE TITLE
Need text cleanup in Enable SD Card Access dialog

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1638]
Add punctuation and spaces between sentences.
![screenshot_2016-10-07-18-11-06](https://cloud.githubusercontent.com/assets/8171759/19206842/7f675ba6-8cb1-11e6-83a5-5b7d36785a6d.png)

**Comment by cckozie** [comment]
Waiting for input from Christine.

**Comment by ChrisJarka** [comment]
The displayed text is even worse on my Android phone.

![capture _2017-03-03-15-31-15](https://cloud.githubusercontent.com/assets/9850185/23568358/20550240-0028-11e7-96bd-aa4223d8a36f.png)

**Comment by ChrisJarka** [comment]
If I select Skip - assuming that it is the 'skip' at the bottom of this screen - I am returned back to where I choose between Internal or SD Card.

Then - I can only save to the root of the SD Card. Is that (saving only to the SD Card root) an expected action of Android?

**Comment by ChrisJarka** [comment]
Biggest problem I see is the end user remembering the steps once they tap off of the first screen.

Is there a way that the initialization could happen and then either as a continuation or returned back to the app and then initialize a save again and this time go through the same steps as directed in tS to the directory to save?

**Comment by ChrisJarka** [comment]
![save to sd](https://cloud.githubusercontent.com/assets/9850185/23860157/78e1a330-07dc-11e7-81da-1d495b78e765.png)

**Comment by PhotoNomad0** [comment]
@ChrisJarka - I can fix the formatting of message (discovered it was being stripped out).

As far as changing behavior of enabling SD card access, this is Google's UI design and for security reasons we cannot change it.  Other apps pop up the same ugly screen as we have to.

**Comment by PhotoNomad0** [comment]
> Is there a way that the initialization could happen and then either as a continuation or returned back to the app and then go through the same steps as directed in tS to the directory to save?

@ChrisJarka - I don't understand what you are saying here.

**Comment by PhotoNomad0** [comment]
> After I have chosen SD Card - and it is initialized - I can only save to the root/base of the SD Card. All folders (already present or just now created by me) fail on save with this message:
> Access Attempt - Failed on access request to: content: //com.android.externalstroage.document/tree/3838-6361%3Adata You may have selected a folder other than the SD CARD base.

@ChrisJarka  - What device are you using here?  I haven't seen this behavior.

**Comment by PhotoNomad0** [comment]
@ChrisJarka - btw that error dialog is one we pop up when the system denies our request for access using the keys the system returned to us.  There is a small chance that the error could be because we could not find the real path to the folder.  Investigating that.

**Comment by ChrisJarka** [comment]
@PhotoNomad0 
I can fix the formatting of message (discovered it was being stripped out).

What is the message without the 'stripping out'? Is it possible to number the steps instead of using asterisks?

**Comment by ChrisJarka** [comment]
@PhotoNomad0 
Is there a way that the initialization could happen and then either as a continuation or returned back to the app and then go through the same steps as directed in tS to the directory to save?

I'll see if this is more clear: 
1) I select to export a file - the file manager opens
2) I select the SD Card - the 'enable' message shows - I choose to continue
3) The message goes away! Another popup with choose internal memory or SD Card shows. Also has the 3-dot menu at the top right - - - Can a message show what is the next step? (click on the SD card icon)
OR
3) The message goes away! Another popup with choose internal memory only showing. Also has the 3-dot menu at the top right. - - - Can a message show what is the next step? (click on the 3-dot menu to show SD card)

Does this help?  It is basically having the instructions show when they are needed instead of having the end user try to remember all of the steps/choices they will need to make.

**Comment by ChrisJarka** [comment]
@PhotoNomad0 
For the question ---

> After I have chosen SD Card - and it is initialized - I can only save to the root/base of the SD Card. All folders (already present or just now created by me) fail on save with this message:
> Access Attempt - Failed on access request to: content: //com.android.externalstroage.document/tree/3838-6361%3Adata You may have selected a folder other than the SD CARD base.
> @ChrisJarka - What device are you using here? I haven't seen this behavior.

I'm using Lenovo TAB 2 A10-709F  Android 5.0.1

**Comment by PhotoNomad0** [comment]
@ChrisJarka - what is the Android version on your phone?  There is a limitation on devices with Kitkat support that Google will not allow third party apps to write to the SD cards, but can only read from them.

**Comment by ChrisJarka** [comment]
Android 5.0.1 
Kernel Version 3.10.61

**Comment by PhotoNomad0** [comment]
> I'm using Lenovo TAB 2 A10-709F Android 5.0.1

@ChrisJarka - Not sure what is happening here - that is the same device I am using.  When this PR gets added to the app, recommend you go into developer tools and "Reset SD Card Access".  Then go through the process again.

Note that we only intended for people for people to provide access to the base folder of the SD Card.  If they select any other folder, then that will be the only folder the user can read/write to.

**Comment by ChrisJarka** [comment]
I just went through the Developer - Advanced - Reset SD Card Access process.
Went back to save to SD - had to confirm enabling the SD card - got fail on saving a USFM and a tstudio to a folder other than the root.
BUT just went back in and saved to two folders (default download and one I made tstudio) with no issues.

Is that the 'trick'? That the user needs to go back to the Upload/Export Options menu and start over again to be able to save to a folder on the SD card?

**Comment by cckozie** [comment]
@PhotoNomad0 I don't understand you last comment to CJ above about the base folder on the SD card. I am able to export files to anywhere I want to on the card.

**Comment by ChrisJarka** [comment]
Build 159 Verbiage suggested changes because there is a mix of metaphors for interacting with choices presented on the Android device. (I will also take this opportunity to make other suggestions on corrections.)

Instead of press and click only use the term 'tap.'  So that the text would read:

Do you want to enable SD card access? If so then:
1) Tap on 'Confirm' at the bottom of this message. This message will close and a new window opens.

2)  If you do not see a SD Card icon in the left column then tap on the 3-dot icon on the top right. Tap on 'Show SD Card.'

3) If the SD Card icon is in the left column then tap on the icon. The files on the SD card show. Tap on the words 'SELECT "SD card"' at the bottom of the window.

If you tap on SKIP below, then Import/Backup will use internal memory.

**Comment by cckozie** [comment]
See CJ's last comment above to standardize on "tap" on the Enable SD card dialog.

**Comment by cckozie** [comment]
Please review CJ's text above and replicate it exactly on the dialog.

**Comment by PhotoNomad0** [comment]
@cckozie - OK - I see that I missed a double quote and have numbers "1)" instead of "1.".  Did I miss anything else?

**Comment by cckozie** [comment]
Remove the single quotes around SD Card in numbers 2 and 3.
Change the period to a comma after window in number 2, and change the capital T to lower case on the following then.
Sorry to be so picky, but I want contributors like CJ to be precise in what they recommend. And I want us to respond precisely to that rather try to figure out what is "close enough" in UI elements. Thanks!

**Comment by cckozie** [comment]
If these changes were made, I don't believe they got rolled into Travis build 1327 as none of changes appear in that build.

**Comment by PhotoNomad0** [comment]
If exact text is to be matched on the button labels, it is appropriate to be quoted.  This was done correctly in step 1 and the end of step 3.  
Will make the other changes.

**Comment by cckozie** [comment]
Sorry I didn't catch this before, but we really need to change "Import/Backup" in the last sentence to "Import/Export".
