### ISSUE TITLE
Save verse markers in text even if not moved

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#1664]
Right now android will not save the verse markers in the text until the user first moves them. However, this can be an issue for chunks that only have one verse. In that case the user may not move it because it already appears to be in the correct location.

**Comment by cckozie** [comment]
The verse markers are now saved, but are now reset by the app. I opened a project that had been pretty much finished with verse markers set correctly. In review mode, I opened a chunk for editing and deleted all of the verse marker text. I closed the edit mode and dragged the verse marker icons to their appropriate places. I then clicked the check mark to reopen the chunk for editing, and all of the verse markers are not at the beginning of the chunk.
The same think happens when entering text into an empty chunk. I entered the text, clicked the check mark, dragged the verse markers to the correct positions, then clicked the pencil icon and the verse marker text is at the beginning of the chunk.

**Comment by cckozie** [comment]
I just ran the above scenario again, and after the verse markers were reset to the top I exited the app. When I reopened the project the verse markers were back to where they were originally. Looks like the changes on the screen were not saved.

**Comment by PhotoNomad0** [comment]
@cckozie - glad you found this.  It looks like this was introduced back in October with all the resource container refactoring.
