### ISSUE TITLE
Problems loading card text when scrolling

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1959]
I created a 1ch project to test another issue. I went to review mode (3 column mode) and used the scroll bar to go to chapter 6 and then swipe scrolled to get to chunk 16. I opened the first Note and clicked the link to go back to chapter 6, verse 1. I then swipe scrolled downward a number of times and when the screen stopped scrolling, the rotating wheels ran for more than 30 seconds before all of the the card text was displayed. This problem also occurs often with just the resources card when I'm in the middle of a project and use the scroll bar to scroll back to the top of the project.

**Comment by neutrinog** [comment]
@cckozie I really don't think you're using the latest build because 1) I cannot reproduce this and 2) I remember specifically adding a fix to handle cases just like this already.

**Comment by cckozie** [comment]
I uninstalled, redownloaded, reinstalled just to make absolutely sure and I still see the issue. Sometimes it's a few <5 seconds, sometimes < 10, sometimes double that or more. Seems to be somewhat dependent on how many cards are on the screen when it stops scrolling.

**Comment by neutrinog** [comment]
ok. turns out the cache was incorrectly getting cleared any time the screen was rotated. That should fix part of the problem when rotating.  I'm still trying to figure out how to fix the super long loading when you scroll. The problem is not all the rendering tasks are getting garbage collected when you scroll which bogs things down. I just haven't determined a fix for it yet.

**Comment by neutrinog** [comment]
@cckozie when you scroll in the list Android is pre-rendering around 11 cards at a time. So if you scroll around a bunch quickly it'll have to render all 11 cards at the same time. If you are scrolling normally it takes just a moment because it only needs to render 1 or 2 new cards.

I tweaked some things so it on average should only take up to 6 seconds to finish loading things. But I don't think we'll be able to squeeze much more out of it. We cache the results of the rendered source and target text, but not the resources because in the past we've quickly hit the memory limit of some devices.

**Comment by cckozie** [comment]
The time it takes to render the text is much better now, but if you rotate the device before it has finished rendering, something unusual happens.
![screenshot_2017-03-13-11-08-07](https://cloud.githubusercontent.com/assets/8171759/23863466/df3dc324-07dd-11e7-9008-9e1d75950cbc.png)

**Comment by neutrinog** [comment]
should be working correctly now.

**Comment by cckozie** [comment]
Still seeing this problem in travis build 1306.
