### ISSUE TITLE
Footnotes are being truncated

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#2065]
This is 1ch chapter 1 chunk 1 English ULB:
[01.usx.txt](https://github.com/unfoldingWord-dev/ts-android/files/880595/01.usx.txt)

This is how it gets rendered using Travis build 1346
![screenshot_2017-03-29-17-50-57](https://cloud.githubusercontent.com/assets/8171759/24480335/64872eb2-14a9-11e7-846f-676e274505c6.png)

**Comment by ChrisJarka** [comment]
Here is tS-Android v11.0 Build 167 with a fresh update of the EN ULB for 1CH installed and being used.
For the footnote of 1CH 1:6 that is:
\v 6 The sons of Gomer were Ashkenaz, Riphath, and Togarmah.
\f + \ft Some versions have \fqa Diphath \fqa* instead of \fqa Riphath \fqa* . However, \fqa Diphath \fqa* was probably a mispelling. Many ancient copies correct it to \fqa Riphath \fqa* in order to make it agree with the same name in Gen. 10:2. \f*

This is what shows in tS-Android 

![bad footnote fqa](https://cloud.githubusercontent.com/assets/9850185/24511972/434e4072-153b-11e7-9558-778829660ee1.png)
