### ISSUE TITLE
Do not show tW resources unless the selected source text is the ULB for the same language.

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#2122]
Change requested by Christine.
Currently tW entries are shown as long as the selected source text is any ULB.

**Comment by cckozie** [comment]
The resource are displayed for my project that has this as its source:
[en_1ti_cck.zip](https://github.com/unfoldingWord-dev/ts-android/files/911215/en_1ti_cck.zip)

**Comment by neutrinog** [comment]
@cckozie that's because the config.yaml has a list of words in it.

**Comment by neutrinog** [comment]
I did make a change so that links with wildcard languages would default to use that of the selected source.
However, since your custom project is defined as an English translation it still picks up the English resources. If you remove the links to the resources (or just deleted the config.yaml file) they will not be shown.

**Comment by cckozie** [comment]
Resources should not be displayed unless the source is a ULB. If I delete the config.yml file it still shows Notes and Questions.

**Comment by neutrinog** [comment]
ah, I forgot the notes and questions were hard coded unlike the words. Now the notes and questions won't be displayed either.

**Comment by cckozie** [comment]
Words will continue to be shown if they are in the config.yml file.
