### ISSUE TITLE
Print to pdf should use the target font size setting

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#2180]
Printed projects should use both the target font and target font size settings. The app currently uses the target font setting but not the target font size setting when printing.

**Comment by PhotoNomad0** [comment]
@cckozie @neutrinog  - the print to PDF was previously using fixed sizes.  I can make the pdf match the screen font size, but there will be a sudden jump in print size by a factor of 2.5 (because the screen and pdf use different units).  I suggest making them track each other keeping the current proportion on sizes (25sp = 10pt).

**Comment by cckozie** [comment]
@PhotoNomad0 I agree that making them proportional sounds like the correct solution.

**Comment by cckozie** [comment]
Text sizing looks good. Wrote up a new issue #2207 to deal with the TOC and page numbers.
