### ISSUE TITLE
Auto save to SD card if Available

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#484]
If an SD card is available then translation work should automatically save to the internal storage and the SD card.

**Comment by jag3773** [comment]
Is it possible to back the apk up to the SD card too?

**Comment by neutrinog** [comment]
note: this wouldn't need to necessarily be the "external sd card". The internal sd card would probably be sufficient.

**Comment by neutrinog** [comment]
this is basically done but need to place the backups into a separate directory.

**Comment by neutrinog** [comment]
The app will now run a service that automatically backups up every 5 minutes.
We need to finish building and cataloging backups so that we have a short but reasonable history of backups for each translations. e.g. for each language there will be a backup for changes made a month ago, week ago, day ago, hour ago, and then 5 min. backups will slowly shift back in time and through each time period and be removed as they drop off the radar.

**Comment by jag3773** [comment]
Can we not store the whole git repo on here?  I was hoping we could effectively do a git push every 5 minutes, retaining all of the history.  Thoughts?

**Comment by neutrinog** [comment]
This is effectively what it's doing. But instead of setting up another repo it's just copying it. This is how the project export (as a translationStudio project not USFM) works. It prepares a zipped archive with the repo. So it retains all the history.
