### ISSUE TITLE
Fix Language Sorting

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#493]
Prefer language code over language name.

For example, if I enter 'en', then the 'en' language row needs to be at the top of the list. Likewise, if I enter 'zh' then zh should be first, zh-tw second, etc.  Current not working example would be 'ta'.

**Comment by jag3773** [comment]
@swilcox did this with tD, may be worth seeing how he did it.

**Comment by neutrinog** [comment]
note to self. Add this to the requirements https://github.com/unfoldingWord-dev/ts-requirements

**Comment by swilcox** [comment]
@neutrinog @jag3773 Looked over here briefly.

In pseudo-code it's something like this:
```
if length of input string is <= 3:
    get languages that have a language_code or country_code that "starts with" the entered string
else:
    get languages where the entered string is found within language_code, language_name, language_region_name
```
Not exactly sure why region_name because entering a region name is going to yield WAY too many results. So I don't think that's probably a useful thing.

entering `es` will yield "Espanyol" and also "es-419 Latin American Spanish". But entering `esperanto` will of course yield "Esperanto".  ;-)

**Comment by neutrinog** [comment]
@leoraj this is in the `com.door43.translationstudio.dialogs.LanguageAdapter`. There's a private class in there named `LanguageFilter`. That should be where you'll need to make the changes.

@jag3773 do you want the languages to be sorted by language code all the time or just when a search is performed?
