### ISSUE TITLE
Psalm Chapter Title Convention

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#756]
Notes
======
Heading for  a chapter  of Psalms  should be singular. e.g. Psalm 32 is correct, Psalms 32 is incorrect.

Environment
======
Environment Key | Value
:----: | :----:
version | 3.0.0
build | 97
UDID | 694f7e286991a5ec
Android Release | 4.4.2
Android SDK | 19
Brand | samsung
Device | degaswifiue

**Comment by neutrinog** [comment]
@jag3773 This is a source issue.

**Comment by neutrinog** [comment]
we may need to have another field in the project json that provides the named to be used with chapter numbers.

**Comment by richmahn** [comment]
Chinese: 
Chinese is even odd/confusing when it comes to Psalms. While they don't have pluralization, they have measure words (classifications) for everything, like we do for "a piece of paper" vs "a ream of paper". For the Bible every chapter is a 章 (zhāng, chapter） EXCEPT for Psalms (诗篇 shī piān), where you never use 章， always 篇 (piān), which literay means “a piece" (a piece of paper, a piece of literary work)...so first chapter of Genesis would be 第一章 but the first Psalm is 第一篇. 

However, it is important to note that many Chinese are ok with one saying 诗篇第一张 （"Psalms Chapter 1"）rather than 诗篇第一篇 ("Psalms Piece 1"), it just isn't as formal, but the former is commonly said in Mainland China (verses the latter commonly used in Taiwan & Hong Kong). So if it doesn't work to have  篇("pian") in the chapter title, but have them all read 章("zhang") that is ok. And you can also write 诗篇1 for Psalm 1, or 诗篇2:15 for Psalm 2:15, thus can avoid this measure word issue all together.

**Comment by jag3773** [comment]
Looks like the USFM standard accounts for this, we'll need to support "\cl", which is defined on page 27 (30) of the USFM Reference Guide.  In short, if "\cl" is used before "\c 1" in a given book, then that code should be used for referring to any given chapter in the book.

Hence, the following USFM should yield a correct result:
```
\s5
\ms Book One
\cl Psalm
\c 1
\p
\q1
\v 1 How fortunate are those who do not do what the wicked people advise them to do,
\q1 who do not imitate the behavior of sinful people,
\q1 and who do not join with people who ridicule God.
...
```

The app should then use "Psalm" to refer to any chapter, e.g. "Psalm 1".  Note that present versions of the ULB/UDB do not have that, but will have it shortly.

**Comment by neutrinog** [comment]
@jag3773  I don't believe that is a fool proof solution. It might be better to provide a new field in the api that gives the correct name to use in chapter titles.

**Comment by neutrinog** [comment]
@jag3773 We really need a generic solution that will work for all projects. Perhaps we can place it in the source like we do the front matter. Just have an extra field that will be used for chapter headings.

**Comment by neutrinog** [comment]
note to self. with the changes to usfm and markdown using the \cl tag will probably be sufficient and we won't need a field in the api.

**Comment by neutrinog** [comment]
There is already a solution to this. Simply use the title field already available to chapters (see obs in the api). This will allow the proper wording to be used in addition to allowing users to translate the chapter titles.
