### ISSUE TITLE
Check text layout in Psalms

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#760]
Notes
======
line spacing and indentation  does not look correct in the  poetry of the Psalms

Environment
======
Environment Key | Value
:----: | :----:
version | 3.0.0
build | 97
UDID | 694f7e286991a5ec
Android Release | 4.4.2
Android SDK | 19
Brand | samsung
Device | degaswifiue

**Comment by jshuma** [comment]
Just made a [pull request](https://github.com/unfoldingWord-dev/ts-android/pull/944) for this one. It makes rendering of Psalms look a lot more like the spec.

However, this issue should stay open since long lines (as in Psalm 1:5) still wrap all the way to the left margin.

![screen shot 2015-10-27 at 5 20 25 pm](https://cloud.githubusercontent.com/assets/7755451/10776554/b2e2189c-7ccf-11e5-8aef-6bd14634b332.png)
