### ISSUE TITLE
Remove Source Language choice

### ISSUE THREAD

**Issue by sampeckham** [unfoldingWord-dev/ts-android#775]
When creating a new project I should not be choosing a source language. It was decided that the project is not dependant on the source language and people may well use more than one.

Instead it should take the user to the Empty Source text screen (see InVision).

This helps teach the user about source texts and demonstrates they can open or select multiple sources. This screen was in an earlier build, so not sure what happened?

**Comment by neutrinog** [comment]
@sampeckham the source language is separate internally. We do have that screen, but you don't see it unless you manually de-select all the source languages on a project.

I thought there was a screen for choosing a starting language as well but I may have interpolated that  because I don't see it in invision now ;)

This'll be a easy fix.
