### ISSUE TITLE
Modal Buttons Style

### ISSUE THREAD

**Issue by sampeckham** [unfoldingWord-dev/ts-android#776]
Actions on modal screen should adhere to Google guidelines.
They should be all uppercase, all in the accent colour and at 20sp.
![screen shot 2015-09-24 at 16 50 06](https://cloud.githubusercontent.com/assets/323212/10078383/5b20bc56-62dc-11e5-9ce0-f17fa2066f1c.png)

**Comment by neutrinog** [comment]
we should be able to change the global style in `src/main/res/values/styles.xml`by adding a style for the modal dialogs.

**Comment by PhotoNomad0** [comment]
My take from this is that we are talking generic styling, not just for Google location?

**Comment by jag3773** [comment]
haha... yes @PhotoNomad0 !

**Comment by sampeckham** [comment]
Updating this issue, we now seem to have at least two different styles of modal window, neither of which match the style guide above.

![screen shot 2015-11-04 at 11 51 30](https://cloud.githubusercontent.com/assets/323212/10937397/75666d12-82ea-11e5-9884-489abdbc34c2.png)

**Comment by neutrinog** [comment]
the target translation info dialog has been updated to reflect the correct design.

**Comment by PhotoNomad0** [comment]
@neutrinog - since you have already fixed the info dialog, I'll take a look at the chunk checklist.

**Comment by PhotoNomad0** [comment]
@sampeckham @neutrinog - In looking at the Chunk Checklist dialog:  that is a dynamically created dialog that will mach the defaults for the device it is running on.  In the case of an older device (e.g. API 16), it will look like the example you posted.  In the case of a newer device (e.g. API ) it will look like that matches the style:

![chunk](https://cloud.githubusercontent.com/assets/14238574/11310754/93d422ec-8f99-11e5-9003-45770ec88b50.jpg)

I am looking into how to apply a custom styles in order to force the dynamic dialogs to look more modern even on old devices.

**Comment by PhotoNomad0** [comment]
@sampeckham @neutrinog - in looking at the Google style guide for button colors, it looks like the dark button color is only for disabled buttons.
