### ISSUE TITLE
Blind Draft Mode - Need whole box clickable

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/ts-android#874]
Lots of people were clicking on the title of the blind draft box and getting frustrated because it wouldn't bring up the cursor and let them type. If the whole box were clickable, it would be more intuitive.

**Comment by jshuma** [comment]
Clarification requested: Is this referring to
(1) being able to click anywhere on the card in review mode that will bring up blind edit mode (instead of having to click specifically on the edit button), or
(2) being able to click anywhere in the screen that shows up *after* clicking that edit button, thus bringing up the cursor?
…or both?

I put together a change implementing (1), but now that I reread the description, I'm not sure whether (1) or (2) is what's intended in this issue.

**Comment by neutrinog** [comment]
this issue is just referring to the blind edit mode (the second button down from the top left menu).

When you swipe to display the target translation (the card with stripes) they want to be able to tap anywhere. Right now there is padding, title, etc. that don't register the click.

I'd suggest making sure the title does not capture click events. There's a parameter you can add to the xml to prevent this.
