### ISSUE TITLE
Add Chapter Numbers to Scroll Bar

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#889]
The scroll bar on the left should show a pop out of the chapter numbers as you fly by.  @sampeckham should know what I'm anticipating here as we discussed this previously.

**Comment by sampeckham** [comment]
Example from NeuBible which uses the same slider concept on the right here.

![img_4610](https://cloud.githubusercontent.com/assets/323212/10815109/ce44eb48-7e21-11e5-816e-d36dc632a707.PNG)

**Comment by jshuma** [comment]
OK, I've started putting together the pieces of this, and I have some initial work [here](https://github.com/jshuma/ts-android/commit/7c3668e6b922e3ee01dcdccd7682ebd3eb7f2720). The general approach is to make a new view on top of the seek bar, displaying chapter numbers (with a background behind them). Normally the chapter numbers don't display, but they alpha-animate into view when the user starts seeking, and they alpha-animate back out when the user stops seeking. There's a hard-coded upper limit of 8 markers (fewer when looking at a book with fewer chapters, and none when looking at a book with only one).

Here's a sample of my initial draft at it. The "#" text is a placeholder for while I get the other relevant logic hooked up.
<img width="213" alt="screen shot 2015-11-24 at 5 09 03 pm" src="https://cloud.githubusercontent.com/assets/7755451/11385567/f5a321d4-92ce-11e5-848d-040cede1682d.png">

Right now it has that characteristic "this is so ugly it must have been designed by a programmer" look to it. :) @neutrinog and @sampeckham, feedback is welcome. I'm happy to make changes as needed (or to go with an entirely different approach).

**Comment by jshuma** [comment]
@neutrinog I added a [pull request](https://github.com/unfoldingWord-dev/ts-android/pull/1069) for this one. The correspondence between the labels and the text position isn't quite perfect. I spent a bunch of time trying to make things line up, but I think this may be nearly as good as it can get without switching to a totally different approach.

Here's what it looks like in a long book:
<img width="533" alt="screen shot 2015-12-07 at 4 36 58 pm" src="https://cloud.githubusercontent.com/assets/7755451/11644514/a103b5f2-9d01-11e5-9e97-b33a7d35b626.png">

…and mid-length:

<img width="875" alt="screen shot 2015-12-07 at 4 36 11 pm" src="https://cloud.githubusercontent.com/assets/7755451/11644518/a9f4188c-9d01-11e5-89e0-793d9f94acce.png">

…also in portrait…

…and in a shorter book:
<img width="530" alt="screen shot 2015-12-07 at 4 37 15 pm" src="https://cloud.githubusercontent.com/assets/7755451/11644529/baaa83be-9d01-11e5-9ad2-5f66af3e57e1.png">

Books with a single chapter don't get highlights.

Highlights are visible only while seeking, and they animate in and out of view to avoid having a jarring user experience.

Works in portrait and in landscape. Tested on Nexus 10 and Nexus 4 (but I didn't test portrait on Nexus 4 since the portrait fixes were on a different branch). Tested on Psalms, James, 3 John, and Mark.

I'm open to any suggestions for refinements, including refinements on the appearance.

**Comment by jshuma** [comment]
I added a few more commits: One to fix merge conflicts, one to update the small-screen layout to relieve crowding (see below), and one to only display the highlights in read mode (since the other modes are indexed by frame, which don't necessarily align with chapters, and where frame numbers aren't meaningful to index by).

<img width="792" alt="screen shot 2015-12-08 at 10 12 35 am" src="https://cloud.githubusercontent.com/assets/7755451/11664332/ffa2da72-9d95-11e5-83c7-3350597292e0.png">
<img width="509" alt="screen shot 2015-12-08 at 10 12 17 am" src="https://cloud.githubusercontent.com/assets/7755451/11664331/ff9e2f72-9d95-11e5-8ff4-13ebd3cc872a.png">
