### ISSUE TITLE
Matthew 23:13-15 Correction Needed

### ISSUE THREAD

**Issue by DonRitchey** [unfoldingWord-dev/ts-android#898]
User working in Matthew 23:13-15 and came across verse 14 which is a footnote hyperlink.   Reference looked up in Translation Studio just to see how that hyperlink would appear.  It shows up as code (needs fixed).  Attached is a screenshot from TS.  Related to Helpdesk ticket 441
![screenshot_2015-10-01-16-18-59](https://cloud.githubusercontent.com/assets/12547128/10488178/6aa02c3c-7265-11e5-93fb-176fcdcec4b0.png)

**Comment by neutrinog** [comment]
@DonRitchey thanks for this. Also, please note there is a new version of translationStudio available for download. You can either install it manually from https://github.com/unfoldingWord-dev/ts-android/releases/tag/3.0.0-104 or via the Google Play Store.

**Comment by neutrinog** [comment]
This is an error in the source text.
The note should be formatted as follows:
```
<note caller="+" style="f">
 <char style="fr">23:14</char>
 <char style="ft">Some authorities insert here, or after v. 12, v. 14</char>
 <char style="fqa">Woe to you, scribes and Pharisees, hypocrites! For you devour windows' houses, while you make a show of long prayers. You will therefore receive greater condemnation.</char>
</note>
```

Please note some `char` elements are missing and others are incomplete/misplaced in the screenshot above.

@jag3773 could you please direct this issue to the appropriate place?

**Comment by neutrinog** [comment]
This is likely due to some missing `\ft` tags in etherpad.
See this issue for details: https://github.com/unfoldingWord-dev/ts-android/issues/551

**Comment by lrsallee** [comment]
I believe this is corrected.

**Comment by DonRitchey** [comment]
Not sure it is fixed unless there is a time delay, as it still is not showing the verse in tS, and in the ULB on door43.org verse 14 is displayed as a footnote (see attached screenshot).  

![matt 23 14 ulb displays as footnote](https://cloud.githubusercontent.com/assets/12547128/10516833/2b99aedc-7328-11e5-843d-50652d9fd613.JPG)

I am still learning so there may be a reason for things still being displayed in this way...thanks for your help!

**Comment by lrsallee** [comment]
Don,

The tS screenshot look correct. Verse 14 is poorly-supported, so we do not want it to display in the text. The only thing the MTT should see is the footnote marker, which appears.

Larry

From: DonRitchey
Reply-To: unfoldingWord-dev/ts-android
Date: Thursday, October 15, 2015 at 10:34 AM
To: unfoldingWord-dev/ts-android
Cc: Larry Sallee
Subject: Re: [ts-android] Matthew 23:13-15 Correction Needed (#898)


Not sure it is fixed unless there is a time delay, as it still is not showing the verse in tS, and in the ULB on door43.org verse 14 is displayed as a footnote (see attached screenshot).

[matt 23 14 ulb displays as footnote]<https://cloud.githubusercontent.com/assets/12547128/10516833/2b99aedc-7328-11e5-843d-50652d9fd613.JPG>

I am still learning so there may be a reason for things still being displayed in this way...thanks for your help!

**Comment by DonRitchey** [comment]
OK, sounds good, thanks for your reply and explanation.

Don

**Comment by neutrinog** [comment]
The source still has a few issues with it. The last bit of verse is spilling out of the marker.

```
<char style="fqa">Woe to you, scribes and Pharisees, hypocrites! for you</char>
  devour widows’ houses, while you make a show of long prayers. You will therefore receive greater condemnation. 
```

This is likely because there is a line break in etherpad. I'm not certain on the formatting used in eitherpad, but I suspect the text is written as follows:
```
\fqa Woe to you, scribes and Pharisees, hypocrites! for you
  devour widows’ houses, while you make a show of long prayers. You will therefore receive greater condemnation. 
```
however it should all be written on a single line:
```
\fqa Woe to you, scribes and Pharisees, hypocrites! for you devour widows’ houses, while you make a show of long prayers. You will therefore receive greater condemnation. 
```

**Comment by lrsallee** [comment]
Joel,

Yes, there was a hidden line break. Not easy to see in Etherpad. I removed it.

Larry

From: Joel Lonbeck
Reply-To: unfoldingWord-dev/ts-android
Date: Thursday, October 15, 2015 at 3:16 PM
To: unfoldingWord-dev/ts-android
Cc: Larry Sallee
Subject: Re: [ts-android] Matthew 23:13-15 Correction Needed (#898)


The source still has a few issues with it. The last bit of verse is spilling out of the marker.

<char style="fqa">Woe to you, scribes and Pharisees, hypocrites! for you</char>
  devour widows’ houses, while you make a show of long prayers. You will therefore receive greater condemnation.


This is likely because there is a line break in etherpad. I'm not certain on the formatting used in eitherpad, but I suspect the text is written as follows:

\fqa Woe to you, scribes and Pharisees, hypocrites! for you
  devour widows’ houses, while you make a show of long prayers. You will therefore receive greater condemnation.


however it should all be written on a single line:

\fqa Woe to you, scribes and Pharisees, hypocrites! for you devour widows’ houses, while you make a show of long prayers. You will therefore receive greater condemnation.
