### ISSUE TITLE
need to support rendering "qr" styles

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#917]
See Psalms 3 UDB for an example

**Comment by neutrinog** [comment]
A lot of the boiler plate already exists. You could probably start by copying one of the other rendering methods and just tweak it.

**Comment by jshuma** [comment]
I added an implementation in e101739 and checked it out with Psalm 3:1 UDB. It properly catches the tag and applies appropriate spacing.

Notably, the text inside the paragraph tag for Psalm 3:1 is empty. The spec indicates Psalm 136 as a typical usage of qr styling of a right-aligned block, but the current version of UDB has the relevant text as q2.

With that in mind, I haven't tested this change for non-empty qr paragraphs, since I haven't yet found any examples in UDB.
