### ISSUE TITLE
require at least one translation contributor before backing up.

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#985]
if a target translation does not have at least one translator when being backed up or exported use the information found in the user profile and add a new translator to the target translation.

The backup occurs in `core.Translator.exportArchive` though in order to keep things as decoupled as possible I'd rather not modify this method. Instead let's just add a quick check wherever this method is called (only 4 places).

There are already methods in the `TargetTranslation` for getting and setting translators.

**Comment by neutrinog** [comment]
see https://github.com/unfoldingWord-dev/ts-android/issues/887#issuecomment-154131458

**Comment by jshuma** [comment]
Added a [pull request](https://github.com/unfoldingWord-dev/ts-android/pull/1231). In the case of `BackupDialog`, it works in `onCreateView()` rather than immediately before the calls to `exportArchive()` in the click callbacks because `UploadTargetTranslationTask` uses other means of making the backup. Since I think the intent was to get all the backup cases (not just those that use `exportArchive()`), I put this where the corresponding TODO was. It seems to be doing the right thing.

Also, I ended up doing the same for the publishing use case, since it seems similar. In practice it will only affect translations created prior to 039676ed30557a962454f6dab4605f910f1fcaf4.
