### ISSUE TITLE
add rendering support for "ms" style

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#994]
See Psalms 90 in ULB. The text is

```
<para style="ms">Book Four</para>A Prayer of Moses the man of God.
```

**Comment by neutrinog** [comment]
here is the usx spec http://digitalbiblelibrary.org/static/docs/usx/index.html

**Comment by jshuma** [comment]
Added a [pull request](https://github.com/unfoldingWord-dev/ts-android/pull/1022).

@sampeckham I'd appreciate any feedback you have on this one. I've set this up so that major section headings are displayed inline with the text -- except for major section headings in read mode that appear at the beginning of a chapter; in that case, they're displayed above the chapter heading. The motivation here is that such headings are useful when trying to get a good overview of the text; but, when doing a verse-by-verse translation, it's best to include them in the same place as in the original source text (i.e., inside the verse they most closely align to). But I'd be happy to try to make changes as necessary.

Here's some examples:
Here's what it looks like with a leading major section heading in read mode:
<img width="1268" alt="90r" src="https://cloud.githubusercontent.com/assets/7755451/11376652/ca6d018e-9296-11e5-8778-9b340c44c4a3.png">

And without one, still in read mode (with the chapter heading now at the top, as before):
<img width="1262" alt="89r" src="https://cloud.githubusercontent.com/assets/7755451/11376673/e0aa4196-9296-11e5-8618-8e004a9533d8.png">

Chunk mode:
<img width="1260" alt="chunk" src="https://cloud.githubusercontent.com/assets/7755451/11376679/e9fe11fa-9296-11e5-96b0-16b063a86682.png">


Review mode:
<img width="1240" alt="review" src="https://cloud.githubusercontent.com/assets/7755451/11376682/ecca8062-9296-11e5-9062-244b71d87346.png">

**Comment by neutrinog** [comment]
@jag3773 do you have any thoughts on placement of the major section headings?

**Comment by jag3773** [comment]
What you have there looks good.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer
